openexchangeratesServer: https://openexchangerates.org/api/
openexchangeratesId: 06e7cefea7a84aae8c7d5011adc5f264
giphyServer: https://api.giphy.com/
giphyId: 1DatgqcYbm4nZu0mFQBIqapWHzSjssil
currency: EUR